[package]
name = "windows-timezones"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/kyrias/windows-timezones"
license = "(MIT OR Apache-2.0) AND Unicode-DFS-2016"

[package.metadata.docs.rs]
features = ["chrono-tz", "strum"]

[workspace]
members = ["generate"]

[dependencies]
chrono-tz = { version = "0.8.1", optional = true }
strum = { version = "0.24.1", default-features = false, features = ["derive"], optional = true }

[features]
chrono-tz = ["dep:chrono-tz"]
strum = ["dep:strum"]
